# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85d96cd51121c828a91b33cff7d130a1b90cc22812ea2bac9f1a9c58fb136ae0f1e6fee0cff7f47d30ff105f1c883ef66a31406f4040e4889a0ba3c8a4eb2ddd

test:
  secret_key_base: 7047cbdf4a884173926a327950076b028caedd95461e21b20bd8a4cd92b49ba4dbf6fb00222a5ce230d58647bdaabb63884dd9e5428091bd3209467fc34ea179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
